# GitHub Sponsors configuration
# You can add your sponsorship links here

# github: [your-github-username]
# patreon: your-patreon-username
# ko_fi: your-kofi-username
# custom: ["https://your-website.com/donate"]
