"""Utility modules for binary-mcp."""

from .structured_errors import (
    ErrorCode,
    StructuredBaseError,
    StructuredError,
    create_address_invalid_error,
    create_address_missing_error,
    create_api_error,
    create_breakpoint_hw_limit_error,
    create_breakpoint_set_failed_error,
    create_debugger_no_binary_error,
    create_debugger_not_connected_error,
    create_debugger_not_paused_error,
    create_disassembly_failed_error,
    create_error_from_api_response,
    create_memory_read_failed_error,
    create_memory_write_failed_error,
    create_module_not_loaded_error,
    create_parameter_error,
    create_symbol_not_found_error,
    create_symbol_resolve_failed_error,
    create_timeout_error,
)

__all__ = [
    "ErrorCode",
    "StructuredError",
    "StructuredBaseError",
    "create_address_invalid_error",
    "create_address_missing_error",
    "create_api_error",
    "create_breakpoint_hw_limit_error",
    "create_breakpoint_set_failed_error",
    "create_debugger_no_binary_error",
    "create_debugger_not_connected_error",
    "create_debugger_not_paused_error",
    "create_disassembly_failed_error",
    "create_error_from_api_response",
    "create_memory_read_failed_error",
    "create_memory_write_failed_error",
    "create_module_not_loaded_error",
    "create_parameter_error",
    "create_symbol_not_found_error",
    "create_symbol_resolve_failed_error",
    "create_timeout_error",
]
