name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-plugin:
    name: Build x64dbg Plugin
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.27.x'

    - name: Download x64dbg SDK
      shell: pwsh
      run: |
        Write-Host "Downloading x64dbg release (includes SDK)..."
        # Use snapshot release which includes the SDK
        $releaseUrl = "https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_latest.zip/download"
        Invoke-WebRequest -Uri $releaseUrl -OutFile x64dbg-snapshot.zip -UserAgent "Mozilla/5.0"

        Write-Host "Extracting x64dbg snapshot..."
        Expand-Archive -Path x64dbg-snapshot.zip -DestinationPath x64dbg-snapshot

        Write-Host "Checking for SDK..."
        Get-ChildItem -Path x64dbg-snapshot -Recurse -Directory | Where-Object { $_.Name -eq "pluginsdk" } | Select-Object FullName

        Write-Host "Setting up SDK directory..."
        New-Item -ItemType Directory -Force -Path extern/x64dbg_sdk

        # Find and copy pluginsdk directory
        $pluginsdkPath = Get-ChildItem -Path x64dbg-snapshot -Recurse -Directory | Where-Object { $_.Name -eq "pluginsdk" } | Select-Object -First 1
        if ($pluginsdkPath) {
            Write-Host "Found pluginsdk at: $($pluginsdkPath.FullName)"
            Copy-Item -Recurse -Path "$($pluginsdkPath.FullName)/*" -Destination extern/x64dbg_sdk/
            Write-Host "SDK files copied successfully"
        } else {
            Write-Host "ERROR: Could not find pluginsdk directory"
            Get-ChildItem -Path x64dbg-snapshot -Recurse -Directory | Select-Object FullName
            exit 1
        }

        Write-Host "SDK ready at: extern/x64dbg_sdk"
        Get-ChildItem extern/x64dbg_sdk

    - name: Build x64 Plugin
      shell: pwsh
      run: |
        Write-Host "Building 64-bit plugin..."
        cd src/engines/dynamic/x64dbg/plugin

        New-Item -ItemType Directory -Force -Path build-x64
        cd build-x64

        cmake .. -G "Visual Studio 17 2022" -A x64 `
          -DX64DBG_SDK_PATH="$PWD/../../../../../extern/x64dbg_sdk" `
          -DCMAKE_BUILD_TYPE=Release

        cmake --build . --config Release

        Write-Host "x64 plugin built successfully"

    - name: Build x32 Plugin
      shell: pwsh
      run: |
        Write-Host "Building 32-bit plugin..."
        cd src/engines/dynamic/x64dbg/plugin

        New-Item -ItemType Directory -Force -Path build-x32
        cd build-x32

        cmake .. -G "Visual Studio 17 2022" -A Win32 `
          -DX64DBG_SDK_PATH="$PWD/../../../../../extern/x64dbg_sdk" `
          -DCMAKE_BUILD_TYPE=Release

        cmake --build . --config Release

        Write-Host "x32 plugin built successfully"

    - name: Prepare Release Artifacts
      shell: pwsh
      run: |
        Write-Host "Preparing release artifacts..."
        New-Item -ItemType Directory -Force -Path release

        Copy-Item src/engines/dynamic/x64dbg/plugin/build-x64/Release/x64dbg_mcp.dp64 release/
        Copy-Item src/engines/dynamic/x64dbg/plugin/build-x32/Release/x64dbg_mcp.dp32 release/

        Write-Host "Artifacts prepared in release/"
        Get-ChildItem release/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x64dbg-plugins
        path: release/*

  create-release:
    name: Create GitHub Release
    needs: build-plugin
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: x64dbg-plugins
        path: release/

    - name: Extract Version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Create Release Notes
      run: |
        cat > release_notes.md << 'NOTES_EOF'
        ## Binary MCP Server Release

        ### Pre-built x64dbg Plugins

        This release includes pre-built x64dbg plugins for dynamic analysis:
        - `x64dbg_mcp.dp64` - 64-bit debugger plugin
        - `x64dbg_mcp.dp32` - 32-bit debugger plugin

        ### Installation

        **Quick Install:**
        ```bash
        # Windows
        irm https://raw.githubusercontent.com/Sarks0/binary-mcp/main/install.ps1 | iex

        # Linux/macOS
        curl -fsSL https://raw.githubusercontent.com/Sarks0/binary-mcp/main/install.py | python3 -
        ```

        **Manual Plugin Installation:**
        1. Download the plugin files from assets below
        2. Copy to your x64dbg installation:
           - `x64dbg_mcp.dp64` → `x64dbg/x64/plugins/`
           - `x64dbg_mcp.dp32` → `x64dbg/x32/plugins/`
        3. Restart x64dbg

        ### Features

        **Static Analysis (Ghidra):**
        - 15+ analysis tools
        - Function decompilation
        - API call detection
        - Crypto constant identification

        **Dynamic Analysis (x64dbg):**
        - Live debugging control
        - Breakpoint management
        - Memory inspection
        - Execution tracing

        ### Requirements

        - Python 3.12+
        - Java 21+ (for Ghidra)
        - Ghidra (auto-detected or set GHIDRA_HOME)
        - x64dbg (optional, for dynamic analysis)

        ### Documentation

        - [Installation Guide](https://github.com/Sarks0/binary-mcp/blob/main/INSTALL.md)
        - [README](https://github.com/Sarks0/binary-mcp/blob/main/README.md)
        NOTES_EOF

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.version.outputs.version }}
        body_path: release_notes.md
        files: |
          release/x64dbg_mcp.dp64
          release/x64dbg_mcp.dp32
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
